### ISSUE TITLE
rewrite to Nextflow

### ISSUE THREAD

**Issue by sawibo** [bastiaanvdroest/IDT_SingleUMI_Pipeline#1]
Hey Bastiaan,

Ik heb jouw code als voorbeeld gebruikt om deze pipeline te herschrijven naar Nextflow. Als je geinteresseerd bent kan je eens hier kijken: 
https://github.com/UMCUGenetics/IDT_SingleUMI_Pipeline

Groeten,

Sander

**Comment by bastiaanvdroest** [comment]
Hoi Sander, 

Leuk dat je het verder oppakt om te gaan gebruiken! Ik hoop dat jullie wat aan de code hebben.

Groeten,
Bastiaan
